{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: muffin-wallet
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.podLabels.app }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
{{- end }}
